### ISSUE TITLE
写的很好，希望加上批量创建的功能

### ISSUE THREAD

**Issue by wumj88** [Flowsnow/wlst#1]
写的很好，希望加上批量创建的功能
同数据库往往要创建多个数据源，除用户外其他都一致，请引进list列表这种的

**Comment by Cheney9303** [comment]
you stupid guy, dont you know no money no talk?if you can give the author money,anything will be considered,ok?

**Comment by Flowsnow** [comment]
暂时不考虑加新功能，可自行pr

**Comment by suncle1993** [comment]
暂时不考虑加新功能，可自行pr
